/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegotriki;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author JhosmanM
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    private JLabel[][] posiciones;
    
    public Ventana() {
        initComponents();
        posiciones = new JLabel[3][3];
        asignarPosiciones();
        //setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pos11 = new javax.swing.JLabel();
        Pos12 = new javax.swing.JLabel();
        Pos22 = new javax.swing.JLabel();
        Pos23 = new javax.swing.JLabel();
        Pos13 = new javax.swing.JLabel();
        Pos21 = new javax.swing.JLabel();
        Pos31 = new javax.swing.JLabel();
        Pos32 = new javax.swing.JLabel();
        Pos33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        contador1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        contador2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        botonReiniciar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        labelTurno = new javax.swing.JLabel();
        turnoJugador = new javax.swing.JLabel();
        turnoJugador1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reiniciarContador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 51));

        Pos11.setBackground(new java.awt.Color(204, 204, 204));
        Pos11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos11.setOpaque(true);

        Pos12.setBackground(new java.awt.Color(204, 204, 204));
        Pos12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos12.setOpaque(true);

        Pos22.setBackground(new java.awt.Color(204, 204, 204));
        Pos22.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos22.setOpaque(true);

        Pos23.setBackground(new java.awt.Color(204, 204, 204));
        Pos23.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos23.setOpaque(true);

        Pos13.setBackground(new java.awt.Color(204, 204, 204));
        Pos13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos13.setOpaque(true);

        Pos21.setBackground(new java.awt.Color(204, 204, 204));
        Pos21.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos21.setOpaque(true);

        Pos31.setBackground(new java.awt.Color(204, 204, 204));
        Pos31.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos31.setOpaque(true);

        Pos32.setBackground(new java.awt.Color(204, 204, 204));
        Pos32.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos32.setOpaque(true);

        Pos33.setBackground(new java.awt.Color(204, 204, 204));
        Pos33.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Pos33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pos33.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Pos31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pos32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pos33, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pos13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pos23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pos31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos33, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 400, 400));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugador1.png"))); // NOI18N
        jLabel11.setText("Jugador 1");

        contador1.setBackground(new java.awt.Color(204, 255, 0));
        contador1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        contador1.setText("0");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugador2.png"))); // NOI18N
        jLabel12.setText("Jugador 1");

        contador2.setBackground(new java.awt.Color(204, 255, 0));
        contador2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        contador2.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contador1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contador2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contador1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(contador2))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 290, 150));

        jLabel15.setBackground(new java.awt.Color(153, 255, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pratidaganada.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jLabel15.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel15.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 280, 40));

        jPanel3.setBackground(new java.awt.Color(102, 255, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tres en raya.png"))); // NOI18N
        jLabel16.setText("jLabel16");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 290, 80));

        botonReiniciar.setBackground(new java.awt.Color(51, 255, 0));
        botonReiniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugar de nuevo.png"))); // NOI18N
        botonReiniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(botonReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 160, 30));

        botonSalir.setBackground(new java.awt.Color(51, 255, 0));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        botonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 80, 30));

        labelTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/turno.png"))); // NOI18N
        labelTurno.setText("Turno");
        labelTurno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 120, -1));

        turnoJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        turnoJugador.setText("jLabel4");
        turnoJugador.setPreferredSize(new java.awt.Dimension(41, 54));
        getContentPane().add(turnoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, 50));

        turnoJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N
        turnoJugador1.setText("jLabel4");
        turnoJugador1.setPreferredSize(new java.awt.Dimension(54, 41));
        getContentPane().add(turnoJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, 50));

        jLabel2.setBackground(new java.awt.Color(153, 204, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 180, 120));

        reiniciarContador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reiniciarContador.png"))); // NOI18N
        reiniciarContador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(reiniciarContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoanimado.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pos11;
    private javax.swing.JLabel Pos12;
    private javax.swing.JLabel Pos13;
    private javax.swing.JLabel Pos21;
    private javax.swing.JLabel Pos22;
    private javax.swing.JLabel Pos23;
    private javax.swing.JLabel Pos31;
    private javax.swing.JLabel Pos32;
    private javax.swing.JLabel Pos33;
    private javax.swing.JButton botonReiniciar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel contador1;
    private javax.swing.JLabel contador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelTurno;
    private javax.swing.JButton reiniciarContador;
    private javax.swing.JLabel turnoJugador;
    private javax.swing.JLabel turnoJugador1;
    // End of variables declaration//GEN-END:variables

    private void asignarPosiciones() {
        posiciones[0][0] = Pos11;
        posiciones[0][1] = Pos12;
        posiciones[0][2] = Pos13;
        posiciones[1][0] = Pos21;
        posiciones[1][1] = Pos22;
        posiciones[1][2] = Pos23;
        posiciones[2][0] = Pos31;
        posiciones[2][1] = Pos32;
        posiciones[2][2] = Pos33;
    }
    
    public JLabel[][] getPosiciones(){
        return posiciones;
    }
    
    public JLabel getContador1(){
        return contador1;
    }
    
    public JLabel getContador2(){
        return contador2;
    }
    
    public JButton getBotonReiniciar(){
        return botonReiniciar;
    }
    
    public JButton getBotonSalir(){
        return botonSalir;
    }

    public JLabel getTurnoJugador(){
        return turnoJugador;
    }
    
    public JLabel getTurnoJugador1(){
        return turnoJugador1;
    }
    
    public JButton getReiniciarContador(){
        return reiniciarContador;
    }
    
}
